name: Deploy
on:
  push:
    branches:
      - main
      - staging
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - staging
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      dev_branch: staging
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          clean: false
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json
      - name: Get node_modules path
        uses: actions/cache@v3
        with:
          path: **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: yarn install
        run: yarn install --frozen-lockfile --prefer-offline
      - name: yarn lint
        run: yarn lint
      - name: yarn build
        run: yarn build
      - name: Checkout ${{ env.dev_branch }} Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.dev_branch }}
          path: ${{ env.dev_branch }}
          clean: false
      - name: ${{ env.dev_branch }} Branch Build
        run: yarn && yarn build
        working-directory: ${{ env.dev_branch }}
      - name: Copy to Dist
        run: cp -r ${{ env.dev_branch }}/out out/${{ env.dev_branch }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
        if: ${{ github.event_name == 'push' }}
      
  deploy:
    if: ${{ github.event_name == 'push' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
