name: Deploy
on:
  push:
    branches:
      - main
      - staging
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - staging
permissions:
  contents: read
  pages: write
  id-token: write
env: 
  dev_branch: staging
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      dev_branch: staging
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          clean: false
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: pnpm install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: pnpm lint
        run: pnpm lint
      - name: pnpm build
        run: pnpm build
      - name: Checkout Staging Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.dev_branch }}
          path: ${{ env.dev_branch }}
          clean: false
      - name: ${{ env.dev_branch }} Branch Build
        run: pnpm install && pnpm build
        working-directory: ${{ env.dev_branch }}
      - name: Copy to Dist
        run: cp -r ${{ env.dev_branch }}/out out/${{ env.dev_branch }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
        if: ${{ github.event_name == 'push' }}
      
  deploy:
    if: ${{ github.event_name == 'push' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
